apiVersion: 1

datasources:
- name: Kluster Analysis
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: telegraf
  isDefault: true
  version: 1

  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: admin
